baseURL = 'https://nicholasearl.me/'
languageCode = 'en-us'
title = 'Nicholas Earl'
theme = 'devise'
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, Nicholas Earl"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "cv"
    name = "cv"
    title = "cv"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "publications"
    name = "publications"
    title = "publications"
    url = "https://scholar.google.com/citations?user=nKOYWIEAAAAJ&hl=en&authuser=1"
    weight = -100
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    title = "Categories"
#    url = "/categories/"
#    weight = -90

# Configuration Features
[params]
  description = "Your meta description"      # Your meta description of the site
  header_title = "Nicholas Earl"                 # Your header title
  header_subtitle = "Astrophysics PhD Student, Software Engineer" # Your header subtitle
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory (optional)
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/nmearl"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/nicholas-earl-952b8088/"
  [[params.social]]
    fa_icon = "fab fa-mastodon fa-1x"
    href = "https://mastodon.social/@ionick"
  [[params.social]]
    fa_icon = "fas fa-university fa-1x"
    href = "https://astro.illinois.edu/directory/profile/nmearl2"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "mailto:contact@nicholasearl.me"